### ISSUE TITLE
[Bug] Recently Played Songs doens't work

### ISSUE THREAD

**Issue by LeonardSSH** [adisreyaj/flare#18]
![image](https://user-images.githubusercontent.com/35312043/155890265-53ad4aac-4ea1-4fb2-912c-46b13979d5bd.png)
![image](https://user-images.githubusercontent.com/35312043/155890297-c3046427-5815-44cb-a674-42e1802c3b3b.png)

**Comment by adisreyaj** [comment]
Have you connected your Spotify account?

**Comment by LeonardSSH** [comment]
@adisreyaj yep.

**Comment by LeonardSSH** [comment]
I tried to create another account and connect it to Spotify, same issue.

**Comment by LeonardSSH** [comment]
After a couple tries, same result.

```
Request URL: https://flare.adi.so/cool-stuffs/spotify-last-played/@Leonard
Request Method: GET
Status Code: 500 
Referrer Policy: strict-origin-when-cross-origin
```
Response:
```
{"error":"Something went wrong"}
```

**Comment by adisreyaj** [comment]
![Screenshot 2022-02-28 at 7 18 46 PM](https://user-images.githubusercontent.com/29002760/155994149-e1602c81-e2b7-4f4f-b51b-9669906f08cf.png)
Looks like its working!

**Comment by LeonardSSH** [comment]
I didn't do anything to it, it seems to have resolved itself. 😅

I think you can now close this issue, since the problem has been solved.

**Comment by kavinvalli** [comment]
<img width="1440" alt="Spotify integration doesn't work" src="https://user-images.githubusercontent.com/41034356/156865865-a9c9d98c-be1b-4ec1-bd89-1c75fd6b9f9d.png">

Still doesn't work for me @adisreyaj

**Comment by adisreyaj** [comment]
Hey @kavinvalli, Can you try `disabling` the cache and trying again.

<img width="625" alt="Screenshot 2022-03-05 at 8 58 15 AM" src="https://user-images.githubusercontent.com/29002760/156866026-064c0e7a-05ef-428c-b391-2d0eba85623e.png">

**Comment by kavinvalli** [comment]
> Hey @kavinvalli, Can you try `disabling` the cache and trying again.
> 
> <img alt="Screenshot 2022-03-05 at 8 58 15 AM" width="625" src="https://user-images.githubusercontent.com/29002760/156866026-064c0e7a-05ef-428c-b391-2d0eba85623e.png">

Still doesn't work @adisreyaj

**Comment by adisreyaj** [comment]
Cool. Let me check what's going wrong!

**Comment by kavinvalli** [comment]
@adisreyaj Do you not have to pass the client id here
https://github.com/adisreyaj/flare/blob/193ab32f106504ab85af338a7718e96e298aaff0/netlify/functions/spotify-last-played/spotify-last-played.ts#L40-L43

**Comment by kavinvalli** [comment]
https://developer.spotify.com/documentation/general/guides/authorization/code-flow/#request-a-refreshed-access-token
<img width="367" alt="Screenshot 2022-03-05 at 09 16 04" src="https://user-images.githubusercontent.com/41034356/156866496-613450c2-3286-4e4f-9359-ece82c71433a.png">

**Comment by adisreyaj** [comment]
@kavinvalli Only required for PKCE based flow. The issue seems to be because of the development mode of Spotify API. Users need to be explicitly added right now. This is a limitation of the Spotify API when in dev mode.

**Comment by adisreyaj** [comment]
Can you try authorizing one more time? I have cleared the data from redis.

**Comment by kavinvalli** [comment]
> @kavinvalli Only required for PKCE based flow. The issue seems to be because of the development mode of Spotify API. Users need to be explicitly added right now. This is a limitation of the Spotify API when in dev mode.
> 
> But I'll investigate further on it.
> 
> Thanks for raising the issue. Let me know if you found something as well.

Oh yes yes, I had that issue too. I don't think there's a workaround. You just have to push it to production

**Comment by kavinvalli** [comment]
@adisreyaj still having the issue. I refresh the app got a 403 saying "Not Configured". Then I connected my spotify account again, again getting a 500 error

**Comment by kavinvalli** [comment]
Still getting the issue @adisreyaj

**Comment by adisreyaj** [comment]
Hey, @kavinvalli will update you when I have some clarity on the Spotify API situation.
